### ISSUE TITLE
Help contribute to p5play!

### ISSUE THREAD

**Issue by quinton-ashley** [quinton-ashley/p5play#227]
Help wanted! Take a look at the p5play project planning cards.

https://github.com/quinton-ashley/p5play/projects/1

To start contributing let me know what you're interested in on the #planning-forum channel of the p5play discord.

https://discord.gg/3UTbqUgmPF

**Comment by Maxwick456** [comment]
I don't have discord BUT I would like to claim this card https://github.com/quinton-ashley/p5play/projects/1#card-88367604

Thanks!

**Comment by quinton-ashley** [comment]
@Maxwick456 awesome! Could you make an account on Discord? That way we could talk about this and the rest of the community could comment too (not everyone has a Discord account).

**Comment by Maxwick456** [comment]
![image](https://user-images.githubusercontent.com/74848706/235370952-cb93e4be-ed03-4c12-8c49-56b7482a5586.png)
um, do you know anything to get around my district's filtering, Proxys don't work

**Comment by quinton-ashley** [comment]
@Maxwick456 Do you have experience making multiplayer servers with socket.io? I've use socket.io but not for gaming.

**Comment by quinton-ashley** [comment]
@Maxwick456 Check this out: https://github.com/quinton-ashley/p5play-web/blob/main/v3/p5play.js#L5799

**Comment by Maxwick456** [comment]
Hi, I am currently working on the socket.io thing, but it is interesting, At the moment I have final tests. During the summer I will be working on coding like 12 hours a day, and I plan on building a pc and will install discord and as much as I can until my mental capacity runs out, anyways Ms.boone is telling me that I am not supposed to be in this website right now since I am in school, I will _**Try**_ As much as I can to be in touch, Also I could collaborate if we were to ues pushbullet.com my email is maxwick456@gmail.com.

**Comment by quinton-ashley** [comment]
@Maxwick456 alright! Yeah focus on your finals first and let me know when you're ready to collaborate.

**Comment by Maxwick456** [comment]
Hey, I think we should create a slack server if you already don't have one! Slack isn't blocked on school chromebook! I have created a channel for my company! If you want to create one or join mine: https://join.slack.com/t/newworkspace-7y33039/shared_invite/zt-1ukzpg51g-emdc9U1pmrwl20~KrVaiBw

**Comment by quinton-ashley** [comment]
Okay sure! Here I made a slack server for p5play: https://join.slack.com/t/newworkspace-mut9132/shared_invite/zt-1ujy88zyr-k87vy5EKwxIhwWJK0GTAiQ

**Comment by Maxwick456** [comment]
Awesome!

**Comment by Maximus-Weichers** [comment]
@quinton-ashley Due to recent advances in proxy technology I AM NOW A DISCORD PERSON!!!!!!!
