### ISSUE TITLE
Group.add does not return a value

### ISSUE THREAD

**Issue by calebfoss** [quinton-ashley/p5play#239]
Group's add method is listed as an alias for push, but while push returns true if the sprite was added, add only calls push and doesn't return its value.

**Comment by quinton-ashley** [comment]
Thank you @calebfoss for all these issue reports! :) I will try fixing them all either later today or tomorrow.

**Comment by quinton-ashley** [comment]
For this issue I realized that in a standard JS array push should return the length of the array after stuff is added so I will implement that.

**Comment by GoToLoop** [comment]
I believe making _Group_.**add()** chainable is much more useful than returning its current _length_; given we can easily get its _length_ later for other means.

**Comment by quinton-ashley** [comment]
@GoToLoop by chain-able do you mean having it return the group?

Also Array.push accepts multiple sprites as arguments so I will make group.push and group.add able to do that as well if that's what you mean.

**Comment by quinton-ashley** [comment]
fixed in v3.6.8
