### ISSUE TITLE
p5play and Device orientation

### ISSUE THREAD

**Issue by gracywhelihan** [quinton-ashley/p5play#246]
When trying to use device orientation for mobile, p5play seems to be blocking the permission from asking the user if they will allow access. So, you cannot use that info to create games.

**Comment by quinton-ashley** [comment]
That problem isn't related to p5play. Device orientation can only be accessed in secure (HTTPS) contexts.

https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events/Detecting_device_orientation
