### ISSUE TITLE
undefined "setting resize" error

### ISSUE THREAD

**Issue by botaro** [quinton-ashley/p5play#251]
its was working up until yesterday, but today i am getting the following error.

play.js:7270 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'resize')
 
please advise.

**Comment by quinton-ashley** [comment]
Can you explain what you're trying to do?

**Comment by quinton-ashley** [comment]
Ah I found the problem, fixed in 3.10.5

**Comment by botaro** [comment]
thank you! its fixed! but what was the problem? why did it happen so sudden?
