### ISSUE TITLE
Animation missing

### ISSUE THREAD

**Issue by lounsen** [quinton-ashley/p5play#252]
[Sprite_sheet_Tilemap_Scene_demo.zip](https://github.com/quinton-ashley/p5play/files/12310277/Sprite_sheet_Tilemap_Scene_demo.zip)
I been working on this little project since July, animations(and Sprites) suddenly went missing due to the update.

I dowloaded version 3.9 (use local script), it all back to normal.

**Comment by quinton-ashley** [comment]
thank you for reporting this, I will try and find the problem!

**Comment by quinton-ashley** [comment]
Fixed in v3.10.8!  The animations were loading fine, the problem was a compatibility issue with the camera the scene manager. Let me know if you notice any other issues.
