### ISSUE TITLE
Can't access Globals section of full documentation

### ISSUE THREAD

**Issue by rainbow-lazer** [quinton-ashley/p5play#272]
Not sure if it's just me, but all the links under [Globals on the full documentation page](https://p5play.org/docs/global.html) seem like they are broken (it just links to the Sprites page).

**Comment by quinton-ashley** [comment]
See my response on:
https://github.com/quinton-ashley/p5play-web/issues/14

But yeah I will try fixing that for the next update, thanks for reporting!

**Comment by rainbow-lazer** [comment]
Got it, thanks!
