### ISSUE TITLE
Bug in 3.15 when trying to detect a group sprite overlapping with a sprite

### ISSUE THREAD

**Issue by rahji** [quinton-ashley/p5play#275]
It seems like `myGroup.overlapping(aSprite)` is not working in 3.15. It works fine in 3.14. 

Please see the repo here for an example I made to show the issue: https://github.com/rahji/broken_overlappinggroup

**Comment by quinton-ashley** [comment]
The issue has already been fixed in the latest version, v3.15.7. I tested it and it worked.

**Comment by rahji** [comment]
Very strange. That's the version in the repo I linked as far as I can tell. I downloaded again to be sure and it's the same problem. Were you able to clone the repo and see the issue?

**Comment by quinton-ashley** [comment]
I did clone the repo and verified that there is no issue with v3.15.7

**Comment by quinton-ashley** [comment]
oh wait sorry

**Comment by rahji** [comment]
glad I'm not totally crazy! 😆

**Comment by quinton-ashley** [comment]
Ah there was a problem with the `sprite.addDefaultSensors` function which is used internally the first time an overlap check occurs. The problem only affected sprites which had their collider type changed to "none" (not set in the constructor). Thanks for reporting the issue!

Fixed in v3.15.8
