### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by Honeybee4642** [quinton-ashley/p5play#279]
When I write a p5play function it shows it as an error. But it still functions. It would be nice if it did not show as an error message.

**Comment by quinton-ashley** [comment]
What editor are you using?

**Comment by quinton-ashley** [comment]
I've never seen Visual Studio Code show an error like that for JavaScript by default, so maybe it's an extension you're using?

Try adding support for p5play auto-completion:
https://github.com/quinton-ashley/p5play/wiki/FAQ#how-do-i-enable-auto-completion-in-visual-studio-code
