### ISSUE TITLE
`world.rayCast`

### ISSUE THREAD

**Issue by quinton-ashley** [quinton-ashley/p5play#280]
Add raycasting.

Override planck's `world.rayCast`

https://piqnt.com/planck.js/RayCast

**Comment by codingMASTER398** [comment]
PLEASE! this would be great for multiplayer games. For now, firing a bullet extremely fast should do the trick. Could also help to have an example like this: https://editor.p5js.org/SebastienR/sketches/2rGNT5FNS

**Comment by quinton-ashley** [comment]
added in v3.20.4
