### ISSUE TITLE
Does p5play impact the p5 DOM functions?

### ISSUE THREAD

**Issue by zoebachman** [quinton-ashley/p5play#281]
Hello - not sure if this is an issue with the p5.js web editor or something changed in this library, but one of my student's p5.play projects suddenly stopped working today and it seems like the error is introduced once we link the p5.play library. She built it in the p5 web editor (here's [my copy of her code](https://editor.p5js.org/abachman4/sketches/iXD1MsqIl)). 

She's trying to position her canvas within a larger webpage, but when she calls .position on her canvas element, she now gets an error saying that .position is not a recognized function (here it is in the [p5 documentation](https://p5js.org/reference/#/p5.Element/position)). I was stumped because all of this code was working fine for the past several days until today when she went to present it in class. I tried the .position sample code in a new project and it works fine - until I include the p5.play libraries. I know that in the past you have to separately include the p5 DOM library, but my understanding is that it's no longer the case? I tried it in OpenProcessing and running into the same error. Thanks!

**Comment by GoToLoop** [comment]
Indeed, if p5.play is loaded, **createCanvas()** returns the `<canvas>` element itself!
However, it should return a [**_p5.Renderer_**](https://p5js.org/reference/#/p5.Renderer) object instead.

**Comment by quinton-ashley** [comment]
Ah yes my mistake. Thanks for reporting! Fixed in v3.18.8
