### ISSUE TITLE
not an issue, more of a letting someone know sort of thing

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [quinton-ashley/p5play#288]
this is just to let @quinton-ashley I'm using your p5Play libraries for a project, and when making the game the intro sequence kept playing over and over again and just got annoying with the scene switching, so I disabled the intro sequence on my project, but added the "made with p5Play" image into the main menu of my game. 

my point is if I were to publicly shared this (and possibly monetized it with a license in the future) would this cause any conflict, or break any terms of use with the library?

**Comment by quinton-ashley** [comment]
yes that would be fine
