### ISSUE TITLE
Complete controller test

### ISSUE THREAD

**Issue by quinton-ashley** [quinton-ashley/p5play#294]
Add indicators for all standard buttons, triggers, and sticks.

https://openprocessing.org/sketch/2120550

**Comment by Metamere** [comment]
I made a more complete test this week for aiding in my game development, so I'll add a few finishing touches and share it.

**Comment by Metamere** [comment]
I took a few hours today to complete the controller tester sketch. You can review it here: https://openprocessing.org/sketch/2225968
I made it responsive, so it should work for the p5play website as well.

**Comment by Metamere** [comment]
I improved it a bit to include a check for analog triggers so it will add little slider columns only when present, as well as some more details regarding button labels for different controller types. I'm pretty proud of the custom drawn sprites for the sticks, how they turn to ellipses accurately when angled out. Do you think I should create a stick function so there's less repetition in the code? Probably fine how it is.

**Comment by quinton-ashley** [comment]
Awesome! It looks so good! Just published a fork of it here.

https://openprocessing.org/sketch/2227913

I'll add a link to it on p5play.org as well!
