### ISSUE TITLE
changing a sprite's image opacity

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [quinton-ashley/p5play#295]
so I've been looking into a way to change a sprite's opacity based on it's distance away from a "light source" making it slowly become less visible as it moves further away, the issue is I'm using the tint() to do so and it prevents me from allowing multiple sprites to have their own levels of visibility based on their distance from the "light source", this issue is only when I apply images to the sprites I have a different system using rgba that works fine without images, but I was wondering if there was a method that works without applying one tint to every sprite in the canvas, or a way to reduce visibility in a sprite without making it fully invisible.

**Comment by UltraHispeed-Elite** [comment]
here's some of the code used for the method without images:

var player;
var enemy;

var c;
var d = [];
var e = [];
var g = [];
var h = [];
var vx = [];
var vy = [];
var v = [];
var cv = [];
var dave;

function setup() {
  createCanvas(600,600);
  
  player = new Sprite(300,300,64,64);
  player.rotationLock = true;
  player.visible = true;
  
  enemy = new Group();
  enemy.rotationLock = true;
  
  for(let i=0; i<1; i++){
    new enemy.Sprite(200+(i*5),200+(i*5),50,50);
  }
  
  createLight(0,0,600,600);
  spriteLight();
  
  console.log(allSprites[1].x);
}

function draw(){
  background("black");
  
  spriteLight();

  playerMovement();
}

function createLight(x1, y1, x2, y2){
  let xc = (x1+x2)/2;
  let yc = (y1+y2)/2;
  c = (xc+yc)/2;
}

function spriteLight(){
  d.length = allSprites.length;
  e.length = allSprites.length;
  g.length = allSprites.length;
  h.length = allSprites.length;
  vx.length = allSprites.length;
  vy.length = allSprites.length;
  v.length = allSprites.length;
  cv.length = allSprites.length;
    
  for(let i = 0; i<allSprites.length; i++) {
    d[i]=0;
    e[i]=0;
    g[i]=0;
    h[i]=0;
    vx[i]=0;
    vy[i]=0;
    v[i]=0;
    cv[i]=0;
    data(i);
  }
}

function data(a) {
  if(allSprites[a].x < c) {
    d[a] = c - allSprites[a].x;
    e[a] = (d[a]/c)*100;
  }else if(allSprites[a].x > c) {
    d[a] = allSprites[a].x - c;
    e[a] = (d[a]/c)*100;
  }else {
    d[a]=0;
    e[a]=0;
  }
    
  if(allSprites[a].y < c) {
    g[a] = c - allSprites[a].y;
    h[a] = (g[a]/c)*100;
  }else if(allSprites[a].y > c) {
    g[a] = allSprites[a].y - c;
    h[a] = (g[a]/c)*100;
  }else {
    g[a]=0
    h[a]=0;
  }
    
  vx[a] = 100-e[a];
  vy[a] = 100-h[a];
  v[a] = (vx[a]+vy[a])/2
  cv[a] = 2.55*v[a];
  colorMode = (HSB, 255)
  allSprites[a].color = (255,255,cv[a]);
  console.log(cv);
}

function playerMovement() {
  if(kb.pressing("w")) {
    player.y -= 5;
  }
  if(kb.pressing("a")) {
    player.x -= 5;
  }
  if(kb.pressing("s")) {
    player.y += 5;
  }
  if(kb.pressing("d")) {
    player.x += 5;
  }
}

**Comment by quinton-ashley** [comment]
Yes sorry I added a new feature to fix this issue in v3.19 but didn't add it to the changelog!

Sprite's now have an opacity setting `sprite.opacity` (changes the canvas's globalAlpha before drawing the sprite)
