### ISSUE TITLE
`allSprites.autoDraw = false` breaks mouse interaction

### ISSUE THREAD

**Issue by rahji** [quinton-ashley/p5play#337]
This simple example works (clicking the sprite changes its size). If, however, you uncomment the two commented lines, mouse clicking no longer works. A workaround is to use `ball.autoDraw = false` instead of `allSprites.autoDraw = false`. Otherwise, setting `autoDraw` to false for `allSprites` seems to work as expected (although I have not tested thoroughly to see if other things are broken besides mouse interaction).

```javascript
let ball;

function setup() {
	new Canvas(500, 500);
	displayMode('centered');

	ball = new Sprite();
	ball.diameter = 50;

	// allSprites.autoDraw = false;
}

function draw() {
	background('skyblue');

	//ball.draw();

	if (ball.mouse.presses()) {
		ball.diameter += 10;
	}
}
```

**Comment by quinton-ashley** [comment]
Thanks for reporting this! Fixed in v3.24.5
